version: '2'
services:
  Balanceador:
    image: registry:18444/rancher/lb-service-haproxy:v0.9.13
    ports:
    - 3030:3030/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
